In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

In [2]:
df = pd.read_csv('Coffe_sales.csv')

In [3]:
df = df.drop(columns=['Weekdaysort', 'Monthsort'])

In [4]:
df.head()

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Date,Time
0,10,card,38.7,Latte,Morning,Fri,Mar,2024-03-01,10:15:50.520000
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,2024-03-01,12:19:22.539000
2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,2024-03-01,12:20:18.089000
3,13,card,28.9,Americano,Afternoon,Fri,Mar,2024-03-01,13:46:33.006000
4,13,card,38.7,Latte,Afternoon,Fri,Mar,2024-03-01,13:48:14.626000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3547 entries, 0 to 3546
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   hour_of_day  3547 non-null   int64
 1   cash_type    3547 non-null   object
 2   money        3547 non-null   float64
 3   coffee_name  3547 non-null   object
 4   Time_of_Day  3547 non-null   object
 5   Weekday      3547 non-null   object
 6   Month_name   3547 non-null   object
 7   Date         3547 non-null   object
 8   Time         3547 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 249.5+ KB

In [6]:
df = df.drop(columns='cash_type')

In [7]:
df = df.drop_duplicates()

In [8]:
df.isnull().sum() / len(df) * 100

hour_of_day    0.0
money          0.0
coffee_name    0.0
Time_of_Day    0.0
Weekday        0.0
Month_name     0.0
Date           0.0
Time           0.0
dtype: float64

In [9]:
df.describe()

       hour_of_day        money
count  3547.000000  3547.000000
mean     14.185791    31.645216
std       4.234010     4.877754
min       6.000000    18.120000
25%      10.000000    27.920000
50%      14.000000    32.820000
75%      18.000000    35.760000
max      22.000000    38.700000

In [10]:
import sys
!{sys.executable} -m pip install ydata-profiling

Requirement already satisfied: ydata-profiling in /opt/miniconda3/lib/python3.13/site-packages (4.18.3)
Requirement already satisfied: scipy<1.17,>=1.8 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (1.16.0)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (2.3.1)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (2.10.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /opt/miniconda3/lib/python3.13/site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (2.3.1)
Requirement already satisfied: minify-html>=0.15.0 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (2.32.3)
Requirement already satisfied: tqdm<5,>=4.66.3 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (0.14.5)
Requirement already satisfied: typeguard<5,>=4 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (4.5.1)
Requirement already satisfied: imagehash==4.3.2 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in /opt/miniconda3/lib/python3.13/site-packages (from ydata-profiling) (0.62.1)
Requirement already satisfied: PyWavelets in /opt/miniconda3/lib/python3.13/site-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /opt/miniconda3/lib/python3.13/site-packages (from imagehash==4.3.2->ydata-profiling) (11.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/miniconda3/lib/python3.13/site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.58.5)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /opt/miniconda3/lib/python3.13/site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in /opt/miniconda3/lib/python3.13/site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in /opt/miniconda3/lib/python3.13/site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/miniconda3/lib/python3.13/site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in /opt/miniconda3/lib/python3.13/site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.1)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/miniconda3/lib/python3.13/site-packages (from pydantic<3,>=2->ydata-profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in /opt/miniconda3/lib/python3.13/site-packages (from pydantic<3,>=2->ydata-profiling) (2.27.1)
Requirement already satisfied: typing-extensions>=4.12.2 in /opt/miniconda3/lib/python3.13/site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/miniconda3/lib/python3.13/site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/miniconda3/lib/python3.13/site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/miniconda3/lib/python3.13/site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/miniconda3/lib/python3.13/site-packages (from requests<3,>=2.32.0->ydata-profiling) (2025.6.15)
Requirement already satisfied: patsy>=0.5.6 in /opt/miniconda3/lib/python3.13/site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: attrs>=19.3.0 in /opt/miniconda3/lib/python3.13/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in /opt/miniconda3/lib/python3.13/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.5)
Requirement already satisfied: puremagic in /opt/miniconda3/lib/python3.13/site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [11]:
from ydata_profiling import ProfileReport

/var/folders/xg/9_zxrtsn0ll10hckyb7z5l780000gn/T/ipykernel_27315/44057814.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install data-profiling via `pip install data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [12]:
profile = ProfileReport(df, title='Coffee Wisdom', explorative=True)

profile.to_file("analysis_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 8/8 [00:00<00:00, 132.66it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]